### ISSUE TITLE
Demo website no loner exists

### ISSUE THREAD

**Issue by Kiddo9000** [eosterberg/terminaljs#13]
[http://www.erikosterberg.com/terminaljs/](http://www.erikosterberg.com/terminaljs/) no longer seems to exist anymore. Nothing else to really say here.

**Comment by commanddotcom** [comment]
I think author abandoned this project a while ago. There are some nice pull request unmerged.

**Comment by eosterberg** [comment]
Hi, yes I have been unactive for a very long time but Im happy to give you access to the repo so you can continue! 

@commanddotcom should I hand it to you since you have a pending pull request?

**Comment by commanddotcom** [comment]
@eosterberg yep, i'm already using **terminaljs** on my [personal website](https://www.workshop200.com/) so i don't mind to take over.

**Comment by commanddotcom** [comment]
https://www.workshop200.com/terminaljs/
