### ISSUE TITLE
Using 'InnerHTML'

### ISSUE THREAD

**Issue by GerhardKreuzer** [eosterberg/terminaljs#3]
Hi Eric,
just want to use the terminalJS in a container like
//document.getElementById("consoleBox").innerHTML = t1.html;
but doesnt work out. Everything other is ok, if I use your addChild construct.
Any suggestions to put it in some container?

Thanks for helping.

With best regards

Gerhard
(Javascript Newbee)

**Comment by eosterberg** [comment]
Hi Gerhard, you need to use the .appendChild() method or the event handlers will be lost and the terminal node will be dead. Adding with .innerHTML is equivalent to initializing new objects.

**Comment by eosterberg** [comment]
So the call should be:
    document.getElementById("consoleBox").appendChild(t1.html);

In this case, .html property is actually a DOM object and not a html string. 'html' is actually a confusing property name, I may change that in the future.

**Comment by GerhardKreuzer** [comment]
Hi,

thanks.
Now I have another Problem.
I use AngularJS for Routing and something else and try to use the terminal.
How can I have a partial view using terminal.js?
My first idea writing a directive Fails, for what reason ever.

Here my code:

(function () 
  {
    var terminalDirective = 
        function () 
        {
          var directive = {};
          directive.restrict = 'E';
          var term = new Terminal();
            /*
          directive.template = '<div class="Terminal" style="background: black; margin: 0px; width: 100%; height: 100%; color: white; font-family: Monaco, Courier;">...</div>'
          */
          term.print('Welcome');
          directive.template = term.html;
            /*
          directive.link = function($scope, element, attributes) 
                            {
                              term.print('Welcome');
                              //term.input('Whats your name?', function (input) { term.print('Welcome, ' + input)});
                              console.log(term.html);
                              element.html(term.html);
                            }
                            */
           console.log(term.html);
          return directive;  
        };
    angular.module('geoHostApp').directive('console',  terminalDirective);
  }());

I alwas get some test: [object HTMLDivElement] instead of the terminal.

Any Chance to get it working?

Thanks a lot for helping

With best regards

Gerhard
